### PR TITLE
graceful shutdown fixes

### LINKED ISSUE #121: Graceful shutdown request
Hey Kevin I hope you are doing well. I'm currently working on my next tile-server so naturally recalled your project from tangram-paparazzi days for the server and worker implementation :)

It's not a big deal but I wonder if there is a way to shutdown prime_server worker threads gracefully. Even with quiesce and long shutdown wait time there is only a small chance that worker destructors being called. Since the worker holds a postgres connection it would probably be nice to have it sign-out properly.

Looking at production use cases brought up this TODO  
https://github.com/valhalla/valhalla/blob/master/src/odin/worker.cc#L131
`// TODO: should we listen for SIGINT and terminate gracefully/exit(0)?`

### PR DESCRIPTION
**Pull request by kevinkreiser**
a few years ago now @pjanetzek opened #121 which exposed two issues with the current implementation of graceful shutdown:

1. the poll timeouts for the server and the worker could be (and typically were) longer than the configurable shutdown seconds. this meant that both the server and the workers wouldn't notice that the quiesce thread signaled its time to shutdown and they should stop their serve/work loops. this meant that they would never relinquish control back to the main thread so that it could clean up and exit normally. this is important because typical applications join on the server thread and if it never returns then any state which your application allocated or resources your application reserved can not be cleaned up or freed.
2. instead what happened was the quiesce thread would wait for the shutdown time to elapse and then exit the program, most of the time with the resources still held by main

this pr fixes #121 by changing the contract a little bit:

1. the poll timeout is now hardcoded to 1 second for both the server and worker, given that this code is so incredibly cheap setting a higher timeout on these loops has no adverse performance impact (ive measured this). we then guarantee that the server and worker threads will notice that we are shutting down within a couple seconds of finishing the draining period and thus will always give back control to main to clean up
2. we no longer force everything to exit from the quiesce thread which does allow the various threads to stop on their own and main to exit normally (deallocating anything its created). thinking about it further its really the job of the orchestrating software (k8s or systemd or even a user themselves) who should decide no actually now its time to really kill this process. ive updated the various comments and docs and examples to explain this.

there were a number of other little changes i just felt should be cleaned up so i did those quickly and will comment on the pr diff

### CODE REVIEW

**Comment by kevinkreiser** [comment]
around 300 lines of this diff are new unit tests and moving the readme example into an actual source file

File: prime_server/prime_server.hpp [hunk 1]
```diff
@@ -2,8 +2,8 @@
 
 // some version info
 #define PRIME_SERVER_VERSION_MAJOR 0
-#define PRIME_SERVER_VERSION_MINOR 7
-#define PRIME_SERVER_VERSION_PATCH 2
+#define PRIME_SERVER_VERSION_MINOR 8
+#define PRIME_SERVER_VERSION_PATCH 0
```
Comment (kevinkreiser) [inline prime_server/prime_server.hpp:6]: since the contract is a bit different def worth a minor update

File: prime_server/prime_server.hpp [hunk 2]
```diff
@@ -194,25 +201,31 @@ class worker_t {
...
+// were working on, while it redirects request traffic away from your process to some other handler.
+//
+// serve() and work() poll timeouts are capped to 1 second, so the worst-case delay between
+// shutting_down being set and the loops noticing is 1 second. when setting your orchestrator's kill
+// deadline (e.g. kubernetes terminationGracePeriodSeconds or systemd TimeoutStopSec), account for
+// drain_seconds + 1 second + however long your application needs to clean up after main regains
+// control.
+//
 // NOTE: this is only meant to be called in the main thread at the beginning of your program
-void quiesce(unsigned int drain_seconds = 0, unsigned int shutdown_seconds = 0);
```
Comment (kevinkreiser) [inline prime_server/prime_server.hpp:212]: as mentioned no more forced `exit`, we let the outside signaler decide when to force kill so that we can allow user code to clean itself up

File: src/art.cpp [hunk 3]
```diff
@@ -0,0 +1,87 @@
+//prime_server guts
```
Comment (kevinkreiser) [inline src/art.cpp:1]: this file is all the stuff thats in the readme. now we built it in ci so it never goes out of date, we also use links in the readme to the various sections of code so that we dont have to constantly copy paste from here

File: src/prime_echod.cpp [hunk 4]
```diff
@@ -1,17 +1,13 @@
+#include <cstdlib>
```
Comment (kevinkreiser) [inline src/prime_echod.cpp:1]: for this one and `prime_filed` we stop detaching threads and we make sure to join on them at the end

File: src/prime_filed.cpp [hunk 5]
```diff
@@ -1,16 +1,16 @@
-#include "http_protocol.hpp"
```
Comment (kevinkreiser) [inline src/prime_filed.cpp:1]: same changes as `prime_echod`

File: src/prime_helpers.hpp [hunk 6]
```diff
@@ -1,35 +0,0 @@
-#pragma once
```
Comment (kevinkreiser) [inline src/prime_helpers.hpp:1]: so we had a quiesce config that was a drain time and a shutdown time. now we only have drain time so we dont need all this crap to parse a single number on the command line

File: src/prime_httpd.cpp [hunk 7]
```diff
@@ -1,18 +1,18 @@
...
 
-#include <cstring>
-#include <string>
-
 int main(int argc, char** argv) {
 
   if (argc < 5) {
     logging::ERROR(
         "Usage: " + std::string(argv[0]) +
-        " [tcp|ipc]://server_listen_endpoint[:tcp_port] [tcp|ipc]://downstream_proxy_endpoint[:tcp_port] [tcp|ipc]://server_result_loopback[:tcp_port] [tcp|ipc]://server_request_interrupt[:tcp_port] [enable_logging] [max_request_size_bytes] [request_timeout_seconds] [drain_seconds,shutdown_seconds] [/health_check_endpoint]");
```
Comment (kevinkreiser) [inline src/prime_httpd.cpp:15]: shutdown seconds are gone thats between you and your k8s/systemd

File: src/prime_proxyd.cpp [hunk 8]
```diff
@@ -9,7 +9,7 @@ int main(int argc, char** argv) {
   if (argc < 3) {
     logging::ERROR(
         "Usage: " + std::string(argv[0]) +
-        " [tcp|ipc]://upstream_endpoint[:tcp_port] [tcp|ipc]://downstream_endpoint[:tcp_port] [drain_seconds,shutdown_seconds]");
```
Comment (kevinkreiser) [inline src/prime_proxyd.cpp:12]: same, no more shutdown seconds

File: src/prime_server.cpp [hunk 9]
```diff
@@ -15,6 +11,8 @@
 #include "prime_server.hpp"
 
 namespace {
+constexpr int POLL_TIMEOUT = 1000;
```
Comment (kevinkreiser) [inline src/prime_server.cpp:14]: right so now all our polling sockets (server -> proxy -> workers) which make up the main get work to the worker path of the architecture, will use a simple 1 second time out. this just means we spend more time rolling the loops of those the entities. for unbusy workers this means we advertise ourselves to the proxies more often, for proxies is really has no effect other than they can actually cleanly shutdown. for the unbusy servers this means we check an empty results socket more often as well as checking more often if there are requests to timeout.

in the case of an actually busy service the end result will be no difference

File: src/prime_server.cpp [hunk 10]
```diff
@@ -42,15 +39,13 @@ struct quiescable final {
...
-    std::thread([set, drain_seconds, shutdown_seconds, this]() {
+    std::thread([set, drain_seconds, this]() {
       // wait for SIGTERM to trigger
       int sig = 0;
       if (sigwait(&set, &sig) == 0) {
         draining = true;
         sleep(drain_seconds);
         shutting_down = true;
-        sleep(shutdown_seconds);
-        exit(0);
```
Comment (kevinkreiser) [inline src/prime_server.cpp:53]: removed this forced killing of the entire application which allows main to actually release any resources it may have provisioned for the workers

File: src/prime_server.cpp [hunk 11]
```diff
@@ -467,7 +461,7 @@ worker_t::worker_t(zmq::context_t& context,
                    const std::string& heart_beat)
     : upstream_proxy(context, ZMQ_DEALER), downstream_proxy(context, ZMQ_DEALER),
       loopback(context, ZMQ_PUSH), interrupt(context, ZMQ_SUB), work_function(work_function),
-      cleanup_function(cleanup_function), heart_beat_interval(5000), heart_beat(heart_beat),
```
Comment (kevinkreiser) [inline src/prime_server.cpp:470]: no need for the heartbeat interval anymore we always poll/advertise at 1hz

File: src/prime_server.cpp [hunk 12]
```diff
@@ -558,6 +551,10 @@ void worker_t::work() {
       }
     }
 
+    // if we are shutting down, interrupts and advertising are pointless
+    if (shutting_down())
+      return;
```
Comment (kevinkreiser) [inline src/prime_server.cpp:556]: so its possible that we are being told to shut down. if it happened early enough in this loop for the users call of the interrupt function to notice then it threw, we caught it above and have cleaned up. because we do indeed want to interrupt the worker when that is the case we must rely on this mechanism. but what it means is that below here we check for other interrupts that may have landed on the socket, however if we are already shutting down it will throw and we'll have an uncaught exception. so to preempt all that and also not waste time doing work that is pointless we have an early bail here for shutting down

File: src/prime_server.cpp [hunk 13]
```diff
@@ -584,6 +581,10 @@ void worker_t::advertise() {
   }
 }
 void worker_t::handle_interrupt(bool force_check) {
+  // everything is interrupted
+  if (shutting_down())
+    throw interrupt_t(job & 0xFFFFFFFF);
```
Comment (kevinkreiser) [inline src/prime_server.cpp:586]: like i said, we want that while the users work function is happening, if shutdown starts we need to react, this is the way to achieve that

File: src/prime_serverd.cpp [hunk 14]
```diff
@@ -21,27 +20,35 @@ int main(int argc, char** argv) {
...
   }
 
   // number of jobs to do or server endpoint
-  size_t requests = 0;
+  size_t requests = 0, prime_start = 0, prime_end = 0;
   std::string server_endpoint = "ipc:///tmp/server_endpoint";
   if (std::string(argv[1]).find("://") != std::string::npos)
     server_endpoint = argv[1];
-  else
-    requests = std::stoul(argv[1]);
```
Comment (kevinkreiser) [inline src/prime_serverd.cpp:34]: ok other than changes to the contract as seen in other binaries this code is slightly changed. now it lets you check a range of numbers for prime. i made this change to make the benchmark a bit more realistic. starting at 0 means the first many many many prime checks are trivial computationally and thus any benchmarking you do with it is kind of retarded. you are just measuring socket throughput. by allowing prime testing in high ranges of numbers you actually use some cpu to do some work. this lets you actually see performance increases when you increase parallelism of the workers

File: CMakeLists.txt [hunk 15]
```diff
@@ -1,4 +1,5 @@
 cmake_minimum_required(VERSION 3.5 FATAL_ERROR)
+set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```
Comment (kevinkreiser) [inline CMakeLists.txt:2]: quality of life for vscode users

**Comment by kevinkreiser** [comment]
@copilot review

File: prime_server/prime_server.hpp (hunk 1 above)
Comment (kevinkreiser) [reply prime_server/prime_server.hpp:6]: but actually if i dont want to rev the major version i need to make it backwards compat. i dont want to rev the major version but there are several things that arent not backcompat compliant:

- `quiesce` doesnt `exit()`, if people relied on that they are screwed
- `quiesce` signature changed
- `worker_t` lost a member (i feel like we can ignore this one since people are unlikely to have subclassed this, worth the risk)

so we can add a dead argument back to the `quiesce` signature but adding `exit()` back to it defeats the purpose.

one option would be to add back the forced shutdown functionality but let it be optional, the other option is put it just say its worth the risk and let it be.

i feel like the latter is best, since its a runtime change not a compile time one. 

thanks for the nudge on versioning @nilsnolde

File: src/prime_httpd.cpp [hunk 16]
```diff
@@ -48,9 +48,7 @@ int main(int argc, char** argv) {
   } catch (...) {}
 
   // setup the signal handler to gracefully shutdown when requested with sigterm
-  unsigned int drain_seconds, shutdown_seconds;
-  std::tie(drain_seconds, shutdown_seconds) = parse_quiesce_config(argc > 8 ? argv[8] : "");
-  quiesce(drain_seconds, shutdown_seconds);
+  quiesce(argc > 8 ? std::stoul(argv[8]) : 28);
```
Comment (kevinkreiser) [inline src/prime_httpd.cpp:51]: the good news is that if its an old config that passes eg `28,2` or whatever for drain and shutdown configs, `stoul` will just return 28 and stop at the comma. so shutdown configs are silently ignored
