### PR TITLE
patch autotools for newer toolchains

### LINKED ISSUE #100: Error: possibly undefined macro: m4_esyscmd
Hi,

I'm trying to install on macOS Big Sur 11.2.3 and ran into this issue after running ./autogen.sh.

All of my autotools are installed and up-to-date:

autoconf 2.71
automake 1.16.3_1
zeromq 4.3.4
czmq 4.2.0

Error message:
configure.ac:1: warning: AC_INIT: unsafe as a filename: "prime_server-[m4_esyscmd([./version.sh])]"
configure.ac:23: warning: The preprocessor macro `STDC_HEADERS' is obsolete.
configure.ac:23:   Except in unusual embedded environments, you can safely include all
configure.ac:23:   ISO C90 headers unconditionally.
configure.ac:41: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
configure.ac:41: the top level
configure.ac:1: error: possibly undefined macro: m4_esyscmd
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /usr/local/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1

I've tried looking everywhere online but haven't found a solution to this. Please advise!

Thank you so much!

### PR DESCRIPTION
**Pull request by kevinkreiser**
i believe this fixes #100 

i recently updated to ubuntu 22.04 and was hitting the issue referenced above. i made some tweaks to properly use the buildin macros.

@nilsnolde you were hitting this one too at one point but moved on to cmake. this might work again for you now but i didnt try in arch tbh.

anyway, starting up a fresh docker container of 22.04 exposes the issue and when i checkout this branch it goes away and builds like a charm

this also updates the mac build to the latest build chain in CI

### CODE REVIEW

File: autogen.sh [hunk 1]
```diff
@@ -1,3 +1,5 @@
 #!/bin/bash
+set -e
```
Comment (kevinkreiser) [inline autogen.sh:2]: we should fail if autogen isnt working
